/**
 * Generates every logo file and the brand colour variables from src/styles/brand.json.
 * Run with `npm run brand` after changing brand colours and commit the results.
 */
import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { Resvg } from '@resvg/resvg-js';

interface Brand {
  ink: string;
  accent: string;
  accentOnDark: string;
  paper: string;
  mist: string;
  slate: string;
}

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const brand = JSON.parse(readFileSync(join(root, 'src/styles/brand.json'), 'utf8')) as Brand;

/** Canonical mark, viewBox 0 0 120 120: scattered pieces (accent) turn into rising bars (ink). */
export function markBody(accent: string, ink: string): string {
  return [
    `<rect x="9" y="58" width="14" height="14" rx="3" transform="rotate(-20 16 65)" fill="${accent}"/>`,
    `<circle cx="30" cy="38" r="7" fill="${accent}"/>`,
    `<rect x="19" y="85" width="11" height="11" rx="2.5" transform="rotate(14 24.5 90.5)" fill="${accent}"/>`,
    `<rect x="46" y="66" width="17" height="38" rx="4" fill="${ink}"/>`,
    `<rect x="70" y="45" width="17" height="59" rx="4" fill="${ink}"/>`,
    `<rect x="94" y="22" width="17" height="82" rx="4" fill="${ink}"/>`,
  ].join('');
}

/** Small-size mark (<= 24 px), viewBox 0 0 32 32: two pieces and three wider bars. */
export function smallMarkBody(accent: string, ink: string): string {
  return [
    `<rect x="2" y="9" width="6" height="6" rx="1.5" transform="rotate(-20 5 12)" fill="${accent}"/>`,
    `<circle cx="5.5" cy="22" r="2.8" fill="${accent}"/>`,
    `<rect x="12" y="17" width="5" height="12" rx="1.5" fill="${ink}"/>`,
    `<rect x="19" y="11" width="5" height="18" rx="1.5" fill="${ink}"/>`,
    `<rect x="26" y="4" width="5" height="25" rx="1.5" fill="${ink}"/>`,
  ].join('');
}

const svg = (viewBox: string, body: string) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${viewBox}">${body}</svg>\n`;

/** App icon: navy rounded square (radius 22 %), Off White bars, accent pieces. */
function appIcon(size: number): string {
  const r = size * 0.22;
  const pad = size * 0.2;
  const scale = (size - pad * 2) / 120;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">` +
    `<rect width="${size}" height="${size}" rx="${r}" fill="${brand.ink}"/>` +
    `<g transform="translate(${pad} ${pad}) scale(${scale})">${markBody(brand.accentOnDark, brand.paper)}</g>` +
    `</svg>\n`
  );
}

function write(rel: string, content: string | Buffer) {
  const file = join(root, rel);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`[brand] wrote ${rel}`);
}

write('public/brand/mark.svg', svg('0 0 120 120', markBody(brand.accent, brand.ink)));
write('public/brand/mark-on-dark.svg', svg('0 0 120 120', markBody(brand.accentOnDark, brand.paper)));
write('public/brand/mark-mono.svg', svg('0 0 120 120', markBody(brand.ink, brand.ink)));
write('public/brand/mark-mono-white.svg', svg('0 0 120 120', markBody('#FFFFFF', '#FFFFFF')));
write('public/brand/favicon.svg', svg('0 0 32 32', smallMarkBody(brand.accent, brand.ink)));
write('public/brand/app-icon.svg', appIcon(512));
write('src/app/icon.svg', svg('0 0 32 32', smallMarkBody(brand.accent, brand.ink)));

const png = new Resvg(appIcon(180), { fitTo: { mode: 'width', value: 180 } }).render().asPng();
write('src/app/apple-icon.png', png);

write(
  'src/styles/brand.css',
  `/* Generated by scripts/generate-brand-assets.ts from brand.json. Do not edit by hand. */\n` +
    `:root {\n` +
    `  --brand-ink: ${brand.ink};\n` +
    `  --brand-accent: ${brand.accent};\n` +
    `  --brand-accent-on-dark: ${brand.accentOnDark};\n` +
    `  --brand-paper: ${brand.paper};\n` +
    `  --brand-mist: ${brand.mist};\n` +
    `  --brand-slate: ${brand.slate};\n` +
    `}\n`,
);
